In [3]:
# lecture 4
# numpy practice

import numpy as np 
# create the 1d array
a=np.array([0,2,5])
a



array([0, 2, 5])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
# generate a random array with 3
a.shape


(3,)

In [6]:
print(a[0])
print(a[1])
print(a[2])


0
2
5


In [9]:
# now 2-d array generate 
b=np.array([[0,3,6],[4,6,7]])
print(b)
b.shape # to know its shape, row and vector no in matrix
print("the shape of b is ", b.shape)

[[0 3 6]
 [4 6 7]]
the shape of b is  (2, 3)


In [15]:
# creating numpy array again , practisisng jus

c=np.zeros([3,3])  # we create array with 3x3 dimension for all zeros

print(c)

e=np.full([3,3],8) # to create for all 8

print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [18]:
# generate random array of 8x8 
f=np.random.random((3,4,2))

print(f)

[[[0.45141196 0.86422446]
  [0.29742919 0.72279783]
  [0.82071731 0.03399243]
  [0.51141193 0.26913845]]

 [[0.62917293 0.76485711]
  [0.12342142 0.6244544 ]
  [0.96275276 0.45319017]
  [0.05756879 0.62406111]]

 [[0.44078536 0.6126257 ]
  [0.23846604 0.37007392]
  [0.07714536 0.7085995 ]
  [0.74884456 0.01412537]]]


In [19]:
# create a 4x4 matrix
g=np.eye(4)
print(g)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
# generate an array from 1 to 15 and also adding 1 

h=np.arange(15)+1
print(h)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [25]:
# create lineapace and indices
# linespace
i=np.linspace(0,1,5) # cut the line betwn 0 and 1 into 5 equal distance
print(i)
j=np.indices((4,4))
print(j)

[0.   0.25 0.5  0.75 1.  ]
[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]


In [26]:
# data slicing

x=np.array([1,3,4,5,8,9,11])
x[1:7:2]# [i:j:k] i starting point,j end point, k steps of slicing 

array([3, 5, 9])

In [30]:
# math operation of array

x=np.array([[1,3],[4,5],[7,9]])
y=np.array([[1,2],[3,4],[6,10]])

In [31]:
# boolean array indices
print("x",x)

# boolean array index
print("x shape",x.shape)

x [[1 3]
 [4 5]
 [7 9]]
x shape (3, 2)


In [32]:
print("arraay sum x+y",x+y)

arraay sum x+y [[ 2  5]
 [ 7  9]
 [13 19]]
